server:
  port: 8089
#测试发现 优先使用yml配置文件  后加载properties
person:
  age: 18
  boss: false
  birth: 2017/12/1
  maps: {k1: v1,k2: v2}
  lists:
    -lisi
    -wangwu
  dog:
    name: xiaogou
    age: 12
  last-name: lisisi